[package]
name = "covau-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
fern = "0.6.2"
log = "0.4.21"
musicbrainz_rs = "0.5.0"
serde = "1.0.202"
serde_json = "1.0.117"
specta = "1.0.5"
tokio = { version = "1.37.0", features = ["full"] }
