[package]
name = "covau_wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
libcovau = { path = "../covau", features = [ "wasmdeps" ] }
serde = "1.0.202"

[lib]
name = "covau_wasm"
crate-type = ["cdylib"]
